version: '3.3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'Library'

      MYSQL_USER: 'root'

      MYSQL_PASSWORD: 'password'

      MYSQL_ROOT_PASSWORD: 'root'
    ports:

      - '3306:3306'
    expose:

      - '3306'

    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db:

