# Generated by Django 3.2.15 on 2022-10-01 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Admin_Firstname', models.CharField(max_length=100)),
                ('Admin_Lastname', models.CharField(max_length=100)),
                ('Admin_email', models.EmailField(error_messages={'unique': 'This email has already been registered.'}, max_length=254, unique=True)),
                ('Admin_password', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_name', models.CharField(max_length=100)),
                ('Book_author', models.CharField(max_length=100)),
                ('Book_prize', models.IntegerField()),
            ],
        ),
    ]
